// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6prTkgPKGOgSsZx4cis8-QBWYGUF2cb0',
    appId: '1:189073413369:web:8110b8d4b84758ddb3be28',
    messagingSenderId: '189073413369',
    projectId: 'uconverse-ultra',
    authDomain: 'uconverse-ultra.firebaseapp.com',
    storageBucket: 'uconverse-ultra.appspot.com',
    measurementId: 'G-0CLB5N51YR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRlRWF4b5-oi90SbgQngcyIEbWqBf7K8w',
    appId: '1:189073413369:android:7d51f5176f9fe0b3b3be28',
    messagingSenderId: '189073413369',
    projectId: 'uconverse-ultra',
    storageBucket: 'uconverse-ultra.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhuQ6-uWALr77CyM9Drg3jgztvkoQ1sZk',
    appId: '1:189073413369:ios:140242759663afa1b3be28',
    messagingSenderId: '189073413369',
    projectId: 'uconverse-ultra',
    storageBucket: 'uconverse-ultra.appspot.com',
    iosClientId: '189073413369-e869j0376vblv8hui9icgn7oocsvss37.apps.googleusercontent.com',
    iosBundleId: 'com.example.uconversUltra',
  );
}
